Remove old Bierman restconf from lighty
PANTHEONtech/lighty pull request #1016
Opened 2022-07-06 11:42 UTC by Tobianas

2022-07-06 14:39 UTC, ihrasko requested changes

2022-07-06 14:39 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConf.java
> -import io.lighty.modules.northbound.restconf.community.impl.config.JsonRestConfServiceType;
When you look into `import io.lighty.modules.northbound.restconf.community.impl.config.JsonRestConfServiceType;
` you can see that `DRAFT_02` is still used.

Please remove `JsonRestConfServiceType` completely.

2022-07-06 14:39 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConf.java
> +        RestconfApplication restconfApplication = new RestconfApplication(schemaCtxHandler,
`final`

2022-07-06 14:39 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConf.java
> +        ServletHolder jaxrs = new ServletHolder(servletContainer8040);
`final` - That's our code-style.

2022-07-06 14:39 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConf.java
> -        if (this.restconfProvider != null) {
Why have you removed this?

2022-07-06 14:39 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConf.java
> -    public RestconfImpl getRestconfImpl() {
Are they deprecated - why these are removed?

2022-07-06 14:39 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConfBuilder.java
> -    /**
Why removed?

2022-07-07 09:12 UTC, PeterSuna requested changes
Please also rework Swagger module. There is initializing swagger for Bierman "Draft02" Restconf.

https://github.com/PANTHEONtech/lighty/blob/master/lighty-modules/lighty-swagger/src/main/java/io/lighty/swagger/SwaggerLighty.java#L46

2022-07-07 09:12 UTC, PeterSuna commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConf.java
>          this.inetAddress = inetAddress;
Please update documentation down here.

     /* In standard Oxygen ODL Restconf blueprints there are exposed two additional services:
           - jsonRestconfServiceDraft02 (for bierman implementation)
           - jsonRestconfServiceDraft02 (for bierman implementation)
           - jsonRestconfService (for RFC8040 implementation)
           - jsonRestconfService (for RFC8040 implementation)
           Those services are not expected to be required thus they are not here.
           Those services are not expected to be required thus they are not here.
         */
         
Also, search in ligty for "Bierman" or "Draft02" and update documentation.

2022-07-13 14:05 UTC, PeterSuna requested changes
Please drop this commit [Remove bierman support from swagger](https://github.com/PANTHEONtech/lighty/pull/1016/commits/0f859c0c2cd3229b7196e6daea58d4b9f30118ad)

Tests should be removed together with testing code. And this:
https://github.com/PANTHEONtech/lighty/pull/1016/commits/0f859c0c2cd3229b7196e6daea58d4b9f30118ad#diff-fabde05b02e5ef738875ff318676cc8ab39a2c6c9f8119faf6ee24ec55affccdL59
Could be moved to `Remove bierman restconf` commit.

2022-07-14 10:28 UTC, PeterSuna approved these changes

2022-07-18 08:48 UTC, ihrasko requested changes

2022-07-18 08:48 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConf.java
> +             final DOMActionService domActionService, final DOMNotificationService domNotificationService,
Please fix formatting.

2022-07-18 08:48 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConfBuilder.java
> -    /**
OK

2022-07-18 08:48 UTC, ihrasko commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-helm/helm/lighty-rcgnmi-app-helm/templates/configmaps.yaml
> -        "webSocketPort": 8181,
Are you sure that there is no websocket in RFC8040?

2022-07-18 08:48 UTC, ihrasko commented on lighty-modules/lighty-swagger/src/test/java/io/lighty/swagger/SwaggerLightyDRAFT18Test.java
> -    protected SwaggerLightyDRAFT18Test() {
Please rename files called `DRAFT18` to `RFC8040`.

2022-07-18 08:48 UTC, ihrasko commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app/src/main/resources/example-config/example_config.json
> -        "restconfServletContextPath":"/restconf",
IMO: there is no need to remove `restconfServletContextPath` configuration.

2022-07-18 08:48 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConf.java
> -import io.lighty.modules.northbound.restconf.community.impl.config.JsonRestConfServiceType;
OK

2022-07-18 08:48 UTC, ihrasko commented on lighty-examples/lighty-community-restconf-actions-app/README.md
> +URLs for Swagger (choose RESTCONF [draft18](https://tools.ietf.org/html/draft-ietf-netconf-restconf-18) in upper right corner):
There is nothing to choose from :D

2022-07-18 08:48 UTC, ihrasko commented on lighty-examples/lighty-community-restconf-netconf-app/README.md
> +URLs for Swagger (choose RESTCONF [draft18](https://tools.ietf.org/html/draft-ietf-netconf-restconf-18) in upper right corner):
No more choices :D

2022-07-20 07:06 UTC, ihrasko requested changes

2022-07-20 07:06 UTC, ihrasko commented on lighty-modules/lighty-restconf-nb-community/src/main/java/io/lighty/modules/northbound/restconf/community/impl/CommunityRestConf.java
> +             final DOMActionService domActionService, final DOMNotificationService domNotificationService,
You are using indent of 5 spaces - and that's not correct.

2022-07-20 07:06 UTC, ihrasko commented on lighty-modules/lighty-swagger/src/test/java/io/lighty/swagger/SwaggerLightyDRAFT18Test.java
> -    protected SwaggerLightyDRAFT18Test() {
In a separate commit you can rename draft18 classes to rfc8040.

2022-07-26 10:25 UTC, ihrasko approved these changes

2022-07-26 10:25 UTC, merged