Close RCgNMI instance in smoke tests
PANTHEONtech/lighty pull request #1043
Opened 2022-07-26 15:50 UTC by PeterSuna

Close RcGNMI instance if initialization fails.
Close RcGNMI instance in negative test.
Fix typo

2022-08-10 15:09 UTC, ihrasko commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-module/src/test/java/io/lighty/applications/rcgnmi/module/RcGnmiAppModuleTest.java
> +        assertTrue(module.close());
```
assertTrue(module.initModules());
assertTrue(module.close());

```

2022-08-11 14:06 UTC, ihrasko requested changes

2022-08-11 14:06 UTC, ihrasko commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-module/src/test/java/io/lighty/applications/rcgnmi/module/RcGnmiAppModuleTest.java
> +    private static RcGnmiAppModule rcgnmiModule;
No need to be static.

2022-08-11 14:26 UTC, PeterSuna commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-module/src/test/java/io/lighty/applications/rcgnmi/module/RcGnmiAppModuleTest.java
> +        rcgnmiAppModule.close();
Close, moved to AfterEach method

2022-08-11 14:26 UTC, PeterSuna commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-module/src/test/java/io/lighty/applications/rcgnmi/module/RcGnmiAppModuleTest.java
> +        assertTrue(module.close());
Close, moved to AfterEach method

2022-08-11 14:27 UTC, PeterSuna commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-module/src/test/java/io/lighty/applications/rcgnmi/module/RcGnmiAppModuleTest.java
> +    private static RcGnmiAppModule rcgnmiModule;
Removed

2022-08-15 10:31 UTC, ihrasko approved these changes

2022-08-15 10:31 UTC, merged