Remove entrypoint script from docker lighty apps
PANTHEONtech/lighty pull request #1049
Opened 2022-08-02 10:26 UTC by PeterSuna

Remove entrypoint script usage from docker image since it takes pid 1 in container. Removing this, Java apps will be started with pid 1.
Solve on of bug reported in issue: #1048 #1047 
ID: 1839

2022-08-11 12:50 UTC, ihrasko requested changes

2022-08-11 12:50 UTC, ihrasko commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-docker/src/main/docker/Dockerfile
> +ENTRYPOINT ["java", "-jar", "${lighty.app.jar}"]
We have lost `$JAVA_OPTS`.

2022-08-11 12:50 UTC, ihrasko commented on lighty-applications/lighty-rnc-app-aggregator/lighty-rnc-app-docker/src/main/docker/Dockerfile
> +ENTRYPOINT ["java", "-jar", "${lighty.app.jar}"]
We have lost `$JAVA_OPTS`.

2022-08-12 16:19 UTC, PeterSuna commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-docker/src/main/docker/Dockerfile
> +ENTRYPOINT ["java", "-jar", "${lighty.app.jar}"]
Fixed

2022-08-12 16:19 UTC, PeterSuna commented on lighty-applications/lighty-rnc-app-aggregator/lighty-rnc-app-docker/src/main/docker/Dockerfile
> +ENTRYPOINT ["java", "-jar", "${lighty.app.jar}"]
Fixed

2022-08-15 07:38 UTC, ihrasko approved these changes

2022-08-15 07:39 UTC, merged