Bump upstream versions
PANTHEONtech/lighty pull request #1174
Opened 2022-11-09 10:17 UTC by Tobianas

Adopt:
- odlparent-11.0.1
- infrautils-4.0.1
- yangtools-9.0.1
- mdsal-10.0.2
- controller-6.0.2
- aaa-0.16.3
- netconf-4.0.2

LIGHTY-113

2022-11-09 13:01 UTC, ihrasko requested changes

2022-11-09 13:27 UTC, Tobianas commented on lighty-core/dependency-versions/pom.xml
> -                <version>11.0.1</version>
Changed in all other .pom files

2022-11-11 10:01 UTC, ihrasko requested changes
odlparent 11.0.2
infrautils 4.0.2
yangtools 9.0.2
mdsal 10.0.3
controller 6.0.3
aaa 0.16.4
netconf 4.0.3
bgpcep 0.18.2

2022-11-11 10:12 UTC, ihrasko commented
Please bump bgpcep to 0.18.3.

2022-11-11 13:13 UTC, ihrasko approved these changes

2022-11-11 13:14 UTC, ihrasko commented
OK, done.

2022-11-11 13:32 UTC, merged