Add configuration for not deployed profile
PANTHEONtech/lighty pull request #1345
Opened 2023-04-14 12:58 UTC by Tobianas

Added changes to disable CSRF for localhost only
to make fab54d78 work.

2023-04-14 13:02 UTC, ihrasko requested changes

2023-04-14 13:02 UTC, ihrasko commented on lighty-examples/lighty-controller-springboot-netconf/src/main/java/io/lighty/core/controller/springboot/config/SecurityConfigurationDeployed.java
> + * Copyright (c) 2018-2021 PANTHEON.tech s.r.o. All Rights Reserved.
2023

2023-04-14 13:02 UTC, ihrasko commented on lighty-examples/lighty-controller-springboot-netconf/src/main/java/io/lighty/core/controller/springboot/config/SecurityConfigurationDeployed.java
> +
Remove this empty line.

2023-04-14 14:58 UTC, Tobianas commented on lighty-examples/lighty-controller-springboot-netconf/src/main/java/io/lighty/core/controller/springboot/config/SecurityConfigurationDeployed.java
> + * Copyright (c) 2018-2021 PANTHEON.tech s.r.o. All Rights Reserved.
fixed

2023-04-14 14:59 UTC, Tobianas commented on lighty-examples/lighty-controller-springboot-netconf/src/main/java/io/lighty/core/controller/springboot/config/SecurityConfigurationDeployed.java
> +
removed

2023-04-24 06:51 UTC, ihrasko commented on lighty-examples/lighty-controller-springboot-netconf/src/main/java/io/lighty/core/controller/springboot/config/SecurityConfigurationNotDeployed.java
>                  .disable()
ignore

2023-04-24 07:34 UTC, ihrasko approved these changes

2023-04-24 07:41 UTC, merged