Introduce Lighty-codecs-util
PANTHEONtech/lighty pull request #674
Opened 2021-03-08 09:11 UTC by caladi

Lighty-codecs-util is a replacment for lighty-codecs.
Util classes from lighty-codecs have been moved into new lighty-codecs-util package.
Deprecated methods used in lighty-codecs-util was replaced.

2021-03-09 12:44 UTC, vainyksi requested changes

2021-03-09 12:44 UTC, vainyksi commented on lighty-core/lighty-codecs/src/main/java/io/lighty/codecs/DataCodec.java
> +@Deprecated(forRemoval = true)
please add javadoc where it will be described why we deprecate this

2021-03-09 12:44 UTC, vainyksi commented on lighty-core/lighty-codecs/src/main/java/io/lighty/codecs/api/Deserializer.java
> +@Deprecated(forRemoval = true)
add reasons for deprecation into javadoc for all deprecated classes

2021-03-15 11:25 UTC, vainyksi approved these changes

2021-03-15 16:03 UTC, Pyro2266 requested changes

2021-03-15 16:03 UTC, Pyro2266 commented on lighty-core/lighty-codecs-util/pom.xml
> +            <plugin>
This plugin should not be needed

2021-03-16 11:54 UTC, caladi commented on lighty-core/lighty-codecs-util/src/main/java/io/lighty/codecs/util/JsonNodeConverter.java
> +            // XXX dirty check for end of object. When serializing RPCs with input/output which is not a
Cannot find another way how to handle missing end of object.

2021-03-24 11:58 UTC, merged