Refactor NetconfConfigUtils
PANTHEONtech/lighty pull request #766
Opened 2021-07-14 15:25 UTC by martinbugan-pt

Deprecate old methods in NetconfConfigUtils and provide a new ones for getting configuration and injecting services like in RestconfConfigUtils.

2021-07-19 06:59 UTC, marekzatko requested changes

2021-07-19 06:59 UTC, marekzatko commented on lighty-modules/lighty-netconf-sb/src/main/java/io/lighty/modules/southbound/netconf/impl/util/NetconfConfigUtils.java
> +    public static NetconfConfiguration getNetconfConfiguration(final NetconfConfiguration configurationFrom) {
I dont see the use of this method, is it suppose to copy config? I would delete this .. also lines 163 164 are wrong anyways.

2021-07-19 06:59 UTC, marekzatko commented on lighty-modules/lighty-netconf-sb/src/main/java/io/lighty/modules/southbound/netconf/impl/util/NetconfConfigUtils.java
> +     * Inject services from LightyServices to Netconf southbound configuration.
This does not inject them from LightyServices.. there is no LightyServices reference coming in. Also I think this method is pretty useless, user can do the same thing with one line.

2021-07-19 06:59 UTC, marekzatko commented on lighty-modules/lighty-netconf-sb/src/main/java/io/lighty/modules/southbound/netconf/impl/util/NetconfConfigUtils.java
> +     * Inject netconf client dispatcher to Netconf southbound configuration, it uses {@link LightyServices}.
It does not use LightyServices. I would also delete this method, it does nothing, user can achieve the same thing with one line.

2021-07-28 15:17 UTC, vainyksi requested changes
The idea here should be to unify the config utils classes for NETCONF & RESTCONF.
I think we should specify in more detail what API the util classes should provide and for what the API methods are intended.

2021-12-01 21:20 UTC, closed without merging