Add gNMI simulator quickstart 14.0.x
PANTHEONtech/lighty pull request #777
Opened 2021-07-27 21:01 UTC by caladi

Add main method into gNMI simulator.
 Simulator is configurable through config-file.
 Config-file can be passed using -c parameter.

2021-07-28 11:38 UTC, PeterSuna approved these changes

2021-07-28 13:55 UTC, vainyksi requested changes
remove yang models, we should not need them - user should provide necessary models, we should not need any default models

2021-07-28 13:55 UTC, vainyksi commented on lighty-modules/lighty-gnmi/lighty-gnmi-test/src/test/java/io/lighty/modules/gnmi/test/gnmi/SimulatorCrudTest.java
> +            new String[]{"-c","src/test/resources/json/example_config.json"});
use simulator builder rather, this would add more complexity for tests, might causing issues running tests on different environments
-> revert

2021-08-02 14:40 UTC, vainyksi requested changes

2021-08-02 14:40 UTC, vainyksi commented on lighty-modules/lighty-gnmi/lighty-gnmi-device-simulator/src/main/java/io/lighty/modules/gnmi/simulatordevice/impl/SimulatedGnmiDeviceBuilder.java
>      }
move also `bossGroup`, `workerGroup`, `encondigs` and `gson` to configuration DTO,
then this builder will consist of `from()` and `buidl()` method
This adds possibility to programmatically fully-configure the device with just config DTO.

2021-08-03 09:09 UTC, vainyksi approved these changes

2021-08-03 11:05 UTC, merged