Remove openflow plugin
PANTHEONtech/lighty pull request #801
Opened 2021-08-16 09:23 UTC by rovarga

OpenFlow is not a release-integrated project, hence it should live in a
separate repository. Remove it pending a move to a separate project.

Signed-off-by: Robert Varga <robert.varga@pantheon.tech>

2021-08-23 13:16 UTC, mmiklus approved these changes

2021-08-23 14:14 UTC, ihrasko approved these changes

2021-08-23 14:29 UTC, Pyro2266 requested changes

2021-08-23 14:29 UTC, Pyro2266 commented on README.md
>  | [Jetty Server](/lighty-modules/lighty-jetty-server/) |[OpenFlow w/ RESTCONF](/lighty-examples/)  | |
This line still mentions OpenFlow

2021-08-24 07:03 UTC, ihrasko approved these changes

2021-08-24 07:39 UTC, merged