Add option to Load yang models from class path inside gNMI SB module
PANTHEONtech/lighty pull request #856
Opened 2021-11-24 16:16 UTC by PeterSuna

2021-12-08 14:18 UTC, vainyksi requested changes

2021-12-10 09:30 UTC, PeterSuna commented on lighty-applications/lighty-rcgnmi-app-aggregator/README.md
> +       1. `initialYangsPaths`: Change `INITIAL_FOLDER_PATH`, from the JSON block above, to a folder path, which contains YANG models you wish to load into the datastore.
done

2021-12-10 09:30 UTC, PeterSuna commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app/pom.xml
> +        </dependency>
done

2021-12-10 09:30 UTC, PeterSuna commented on lighty-modules/lighty-gnmi/lighty-gnmi-sb/src/test/java/io/lighty/gnmi/southbound/mountpoint/codecs/testcases/CodecTestCasesBase.java
> +    static final String IT_ID = "openconfig-interfaces";
done

2021-12-10 09:36 UTC, PeterSuna commented on lighty-modules/lighty-gnmi/lighty-gnmi-sb/src/main/java/io/lighty/gnmi/southbound/schema/loader/util/YangLoadModelUtil.java
> +public class YangLoadModelUtil {
YangLoadModelUtil  is called by both ByClassPathYangLoaderService and ByPathYangLoaderService. So this class is tested whenever is called load method in YangLoaderService.
E.q:
https://github.com/PANTHEONtech/lighty/pull/856/files#diff-c4ac418d67e7038568821d00cc4bc5573ed914192bac85d33079d3a6fa270bf9R43

2021-12-13 11:18 UTC, vainyksi approved these changes

2021-12-13 11:46 UTC, merged