Workaround fix for Openconfig regex pattern matching problem - Master
PANTHEONtech/lighty pull request #857
Opened 2021-11-26 14:52 UTC by PeterSuna

Openconfig models regex patterns contains regex posix for start and end of regex pattern. Regex pattern inside
 yang model formatted this way is not supported by YANGTOOLS yet.
 https://jira.opendaylight.org/browse/YANGTOOLS-1005

2021-12-08 17:36 UTC, vainyksi requested changes

2021-12-10 10:09 UTC, PeterSuna commented on lighty-modules/lighty-gnmi/lighty-gnmi-commons/src/main/java/io/lighty/modules/gnmi/commons/util/SanitizeYangModel.java
> +public final class SanitizeYangModel {
done

2021-12-10 10:09 UTC, PeterSuna commented on lighty-modules/lighty-gnmi/lighty-gnmi-commons/src/main/java/io/lighty/modules/gnmi/commons/util/SanitizeYangModel.java
> +    /*
done

2021-12-10 10:11 UTC, PeterSuna commented on lighty-modules/lighty-gnmi/lighty-gnmi-test/src/test/java/io/lighty/modules/gnmi/test/gnmi/rcgnmi/GnmiGetITTest.java
> +    private static String getOcOpenflowJsonResult() {
done

2021-12-13 11:47 UTC, vainyksi approved these changes

2021-12-13 12:26 UTC, merged