Close gracefully lighty application when exception is thrown - Master
PANTHEONtech/lighty pull request #885
Opened 2021-12-22 14:36 UTC by PeterSuna

- Close resources in RcGNMI and RNC application when initialization fail.
-  Increase default timeout for initializing lighty modules to 90s. In reported issue #881 was reported that lighty controller was not   initialized under 60s without addition exception message. Lighty controller initialization contain two future get call with 30s timeout. In case of longer loading, RcGNMI application can close controller initialization while waiting on one of those get calls.
- Close application RcGNMI and RNC application with System.exit(0) when initialization fail.
  Using System.exit(0) should be used with extreme care, and only when the intent is to stop the whole Java process.
  https://rules.sonarsource.com/java/RSPEC-1147 Main method is the only exception where this call can be used.

2021-12-22 15:27 UTC, Pyro2266 requested changes

2021-12-22 15:27 UTC, Pyro2266 commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-module/src/main/java/io/lighty/applications/rcgnmi/module/RcGnmiAppModule.java
> +    private static final long DEFAULT_LIGHTY_MODULE_TIMEOUT = 90;
Do not increase timeout, rather make it configurable.

2021-12-22 15:27 UTC, Pyro2266 commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app-module/src/main/java/io/lighty/applications/rcgnmi/module/RcGnmiAppException.java
> +    public RcGnmiAppException() {
Remove this constructor. Exception should always contain at least message or original cause.

2021-12-22 15:27 UTC, Pyro2266 commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app/src/main/java/io/lighty/applications/rcgnmi/app/RCgNMIApp.java
> +            System.exit(0);
Don't use `System.exit(0)`. If shutdown procedure is done correctly, application should shutdown itself.

2021-12-22 15:27 UTC, Pyro2266 commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app/src/main/java/io/lighty/applications/rcgnmi/app/RCgNMIApp.java
> +                module.shutdown().get();
You can add timeout here

2021-12-22 15:27 UTC, Pyro2266 commented on lighty-applications/lighty-rcgnmi-app-aggregator/lighty-rcgnmi-app/src/main/java/io/lighty/applications/rcgnmi/app/RCgNMIApp.java
> +                stop();
Do not call `stop` here in each error state. Just throw exception and handle it one layer higher (in `main` method in this case.

2021-12-22 15:27 UTC, Pyro2266 commented on lighty-applications/lighty-rnc-app-aggregator/lighty-rnc-app/src/main/java/io/lighty/applications/rnc/app/Main.java
> +            stop();
Don't call `stop` here - same as in rcgnmi

2021-12-22 15:27 UTC, Pyro2266 commented on lighty-applications/lighty-rnc-app-aggregator/lighty-rnc-module/src/main/java/io/lighty/applications/rnc/module/RncLightyModule.java
> +    private static final long DEFAULT_LIGHTY_MODULE_TIMEOUT = 90;
Don't increase timeout, rather make it configurable... same as in rcgnmi

2021-12-23 13:45 UTC, closed without merging

2022-02-03 08:29 UTC, marchest commented
Hi @PeterSuna,

Does this PR cover below issue and q&a ?

https://github.com/PANTHEONtech/lighty/issues/899
https://github.com/PANTHEONtech/lighty/issues/898

Thanks.

2022-02-03 15:13 UTC, PeterSuna commented
Hello, @marchest 
this PR was closed due to review and reworked in PR #886.
Problems that you described could be resolved with that PR #886,  hence there is introduced an option to increase time-out for lighty applications.

2022-02-07 08:39 UTC, marchest commented
> Hello, @marchest this PR was closed due to review and reworked in PR #886. Problems that you described could be resolved with that PR #886, hence there is introduced an option to increase time-out for lighty applications.

Hi @PeterSuna,

Thanks for the response but my issue is not occuring during startup, its being occured 60 seconds after calling netconf server. And doesn't work later on.