Bump upstream versions to the latest phosphorus SR2 - 15.1.x
PANTHEONtech/lighty pull request #915
Opened 2022-02-10 09:48 UTC by PeterSuna

- odlparent-9.0.12
- aaa-0.14.8
- controller-4.0.8
- infrautils-2.0.12
- mdsal-8.0.10
- netconf 2.0.12
- yangtools 7.0.12

Signed-off-by: Peter Suna <peter.suna@pantheon.tech>

2022-02-23 12:54 UTC, ihrasko requested changes

2022-02-23 12:54 UTC, ihrasko commented on lighty-core/dependency-versions/pom.xml
> +                <version>0.14.9</version>
0.14.10

2022-02-23 15:54 UTC, PeterSuna commented on lighty-core/dependency-versions/pom.xml
> +                <version>0.14.9</version>
done

2022-03-01 10:59 UTC, vainyksi approved these changes

2022-03-01 11:01 UTC, merged