Provide module shards Config to Controller instead of tmp file
PANTHEONtech/lighty pull request #938
Opened 2022-03-04 09:08 UTC by PeterSuna

Provide custom moduleShardsConfig in controller instead of storing
moduleShardsConfig in tmp file: "/tmp/module-shards.conf".
This file was later read in initializing class ConfigurationImpl.

2022-04-06 12:34 UTC, ihrasko requested changes
Move this PR to master branch.

2022-04-06 12:34 UTC, ihrasko commented on lighty-core/lighty-clustering/src/main/java/io/lighty/core/cluster/kubernetes/KubernetesClusteringHandlerImpl.java
> +            List<String> memberRoles = akkaDeploymentConfig.getStringList("akka.cluster.roles");
final

2022-04-06 12:34 UTC, ihrasko commented on lighty-core/lighty-clustering/src/main/java/io/lighty/core/cluster/kubernetes/KubernetesClusteringHandlerImpl.java
> +            String data = ClusteringConfigUtils.generateModuleShardsForMembers(memberRoles);
final

2022-04-12 08:19 UTC, PeterSuna commented
Duplicated with #952

2022-04-12 08:19 UTC, closed without merging