Fix not started JUnit test in gNMI
PANTHEONtech/lighty pull request #949
Opened 2022-04-08 08:46 UTC by PeterSuna

When in one project is used Junit4 and Junit5 than only Junit5 test will start with maven build. If in project
is already test with Junit5. Switch other tests to Junit5.

Plaintext mode stop working in gNMI after bumping grpc to higher version than 1.32.3.
https://github.com/grpc/grpc-java/releases/tag/v1.33.0

Response from grpc MannagedChannel after creating plain-text request:
"UNAVAILABLE: Network closed for unknown reason"

When gNMI simulator is created with plain-text option to NettyServerBuilder is assigned also self-signed default
certificates. This works perfectly fine before grpc release 1.33.0 after that if default certificates were assigned sooner than
plaintext, it starts in mixed mode. For gnmic client request for plaintext works fine, but grpc MannagedChannel works only
with insecure mode. 
Removing default certificates from gNMI simulator if plaintext is allowed, resolved this problem.

2022-04-12 12:14 UTC, ihrasko requested changes

2022-04-12 12:14 UTC, ihrasko commented on lighty-modules/lighty-gnmi/lighty-gnmi-device-simulator/src/main/java/io/lighty/modules/gnmi/simulatordevice/impl/SimulatedGnmiDevice.java
> +        if (!StringUtil.isNullOrEmpty(certificatePath) && !StringUtil.isNullOrEmpty(keyPath)) {
Or if you are afraid of this scenario we can raise an error - incorrect configuration when user choose to use plaintext and provide certificates at the same time.

2022-04-13 15:52 UTC, PeterSuna commented on lighty-modules/lighty-gnmi/lighty-gnmi-device-simulator/src/main/java/io/lighty/modules/gnmi/simulatordevice/impl/SimulatedGnmiDevice.java
> +        if (!StringUtil.isNullOrEmpty(certificatePath) && !StringUtil.isNullOrEmpty(keyPath)) {
Done

2022-04-14 08:54 UTC, ihrasko approved these changes

2022-04-14 08:54 UTC, merged